### ISSUE TITLE
Cannot run app.js

### ISSUE THREAD

**Issue by yoshuawuyts** [maxdow/angularjs-requirejs-seed#2]
Whenever running app.js through 

```
node app.js
```

I get a referenceerror: define is not defined. 

I properly installed all the packages through npm prior to running the file.

**Comment by yoshuawuyts** [comment]
```
C:\Users\Yoshua\Documents\GitHub\angularjs-requirejs-seed\src\public\js\app.js:1
(function (exports, require, module, __filename, __dirname) { define(
                                                          ^
ReferenceError: define is not defined
    at Object.<anonymous> (C:\Users\Yoshua\Documents\GitHub\angularjs-requirejs-    seed\src\public\js\app.js:1:63)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:901:3
```

**Comment by maxdow** [comment]
define is the function from require.js.  /public/app.js must be run in the browser, not in node. 

I move public folder to app folder. The app.js will be renamed to server.js
